name: E2E Tests

on: [push, workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: ArtemGCorp/automation-practice
          path: tests

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Start the app
        env:
          CI: ''
        run: |
          yarn install --frozen-lockfile
          nohup yarn webapp:start &
          npx wait-on -t 180000 http://localhost:3000 tcp:localhost:3001

      - name: Run tests in Docker
        run: |
          docker build -f tests/Dockerfile.tests -t testingframework ./tests
          docker run --rm --network host testingframework
